// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.labor23.powercounter.web;

import de.labor23.powercounter.web.GraphBean;
import java.io.Serializable;

privileged aspect GraphBean_Roo_Serializable {
    
    declare parents: GraphBean implements Serializable;
    
    private static final long GraphBean.serialVersionUID = 1L;
    
}
