// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.labor23.powercounter.web;

import de.labor23.powercounter.web.PowerMeterBean;
import java.io.Serializable;

privileged aspect PowerMeterBean_Roo_Serializable {
    
    declare parents: PowerMeterBean implements Serializable;
    
    private static final long PowerMeterBean.serialVersionUID = 1L;
    
}
