// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.labor23.powercounter.web;

import de.labor23.powercounter.web.ShowUserBean;
import java.io.Serializable;

privileged aspect ShowUserBean_Roo_Serializable {
    
    declare parents: ShowUserBean implements Serializable;
    
    private static final long ShowUserBean.serialVersionUID = 1L;
    
}
