// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.labor23.powercounter.web;

import de.labor23.powercounter.web.TickBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TickBean_Roo_Configurable {
    
    declare @type: TickBean: @Configurable;
    
}
