// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.labor23.powercounter.dm;

import de.labor23.powercounter.dm.PowerMeter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PowerMeter_Roo_Configurable {
    
    declare @type: PowerMeter: @Configurable;
    
}
