// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.labor23.powercounter.dm;

import de.labor23.powercounter.dm.PowerMeter;
import de.labor23.powercounter.dm.PowerMeterDataOnDemand;
import de.labor23.powercounter.dm.PowerMeterIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PowerMeterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PowerMeterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PowerMeterIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PowerMeterIntegrationTest: @Transactional;
    
    @Autowired
    PowerMeterDataOnDemand PowerMeterIntegrationTest.dod;
    
    @Test
    public void PowerMeterIntegrationTest.testCountPowerMeters() {
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to initialize correctly", dod.getRandomPowerMeter());
        long count = PowerMeter.countPowerMeters();
        Assert.assertTrue("Counter for 'PowerMeter' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PowerMeterIntegrationTest.testFindPowerMeter() {
        PowerMeter obj = dod.getRandomPowerMeter();
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to provide an identifier", id);
        obj = PowerMeter.findPowerMeter(id);
        Assert.assertNotNull("Find method for 'PowerMeter' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PowerMeter' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PowerMeterIntegrationTest.testFindAllPowerMeters() {
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to initialize correctly", dod.getRandomPowerMeter());
        long count = PowerMeter.countPowerMeters();
        Assert.assertTrue("Too expensive to perform a find all test for 'PowerMeter', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PowerMeter> result = PowerMeter.findAllPowerMeters();
        Assert.assertNotNull("Find all method for 'PowerMeter' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PowerMeter' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PowerMeterIntegrationTest.testFindPowerMeterEntries() {
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to initialize correctly", dod.getRandomPowerMeter());
        long count = PowerMeter.countPowerMeters();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PowerMeter> result = PowerMeter.findPowerMeterEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PowerMeter' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PowerMeter' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PowerMeterIntegrationTest.testFlush() {
        PowerMeter obj = dod.getRandomPowerMeter();
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to provide an identifier", id);
        obj = PowerMeter.findPowerMeter(id);
        Assert.assertNotNull("Find method for 'PowerMeter' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPowerMeter(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PowerMeter' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PowerMeterIntegrationTest.testMergeUpdate() {
        PowerMeter obj = dod.getRandomPowerMeter();
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to provide an identifier", id);
        obj = PowerMeter.findPowerMeter(id);
        boolean modified =  dod.modifyPowerMeter(obj);
        Integer currentVersion = obj.getVersion();
        PowerMeter merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PowerMeter' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PowerMeterIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to initialize correctly", dod.getRandomPowerMeter());
        PowerMeter obj = dod.getNewTransientPowerMeter(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PowerMeter' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PowerMeter' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PowerMeterIntegrationTest.testRemove() {
        PowerMeter obj = dod.getRandomPowerMeter();
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PowerMeter' failed to provide an identifier", id);
        obj = PowerMeter.findPowerMeter(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PowerMeter' with identifier '" + id + "'", PowerMeter.findPowerMeter(id));
    }
    
}
