// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.labor23.powercounter.dm;

import de.labor23.powercounter.dm.Tick;
import de.labor23.powercounter.dm.TickDataOnDemand;
import de.labor23.powercounter.dm.TickIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TickIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TickIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TickIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TickIntegrationTest: @Transactional;
    
    @Autowired
    TickDataOnDemand TickIntegrationTest.dod;
    
    @Test
    public void TickIntegrationTest.testCountTicks() {
        Assert.assertNotNull("Data on demand for 'Tick' failed to initialize correctly", dod.getRandomTick());
        long count = Tick.countTicks();
        Assert.assertTrue("Counter for 'Tick' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TickIntegrationTest.testFindTick() {
        Tick obj = dod.getRandomTick();
        Assert.assertNotNull("Data on demand for 'Tick' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tick' failed to provide an identifier", id);
        obj = Tick.findTick(id);
        Assert.assertNotNull("Find method for 'Tick' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tick' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TickIntegrationTest.testFindAllTicks() {
        Assert.assertNotNull("Data on demand for 'Tick' failed to initialize correctly", dod.getRandomTick());
        long count = Tick.countTicks();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tick', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tick> result = Tick.findAllTicks();
        Assert.assertNotNull("Find all method for 'Tick' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tick' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TickIntegrationTest.testFindTickEntries() {
        Assert.assertNotNull("Data on demand for 'Tick' failed to initialize correctly", dod.getRandomTick());
        long count = Tick.countTicks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tick> result = Tick.findTickEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tick' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tick' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TickIntegrationTest.testFlush() {
        Tick obj = dod.getRandomTick();
        Assert.assertNotNull("Data on demand for 'Tick' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tick' failed to provide an identifier", id);
        obj = Tick.findTick(id);
        Assert.assertNotNull("Find method for 'Tick' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTick(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tick' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TickIntegrationTest.testMergeUpdate() {
        Tick obj = dod.getRandomTick();
        Assert.assertNotNull("Data on demand for 'Tick' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tick' failed to provide an identifier", id);
        obj = Tick.findTick(id);
        boolean modified =  dod.modifyTick(obj);
        Integer currentVersion = obj.getVersion();
        Tick merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tick' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TickIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Tick' failed to initialize correctly", dod.getRandomTick());
        Tick obj = dod.getNewTransientTick(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tick' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tick' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Tick' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TickIntegrationTest.testRemove() {
        Tick obj = dod.getRandomTick();
        Assert.assertNotNull("Data on demand for 'Tick' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tick' failed to provide an identifier", id);
        obj = Tick.findTick(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Tick' with identifier '" + id + "'", Tick.findTick(id));
    }
    
}
